ame: "Python 3.9.6 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.9.2
        - python --version
        - python -m pip install --upgrade pip
        - python -m pip install --upgrade codecov pytest
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
before_install:
  - python --version
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade codecov pytest
install:
  - pip install ".[test]"
script: pytest
after_success:
  - codecov # submit coverage
